//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.06 at 01:43:49 PM CEST 
//


package org.openehr.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for C_ARCHETYPE_ROOT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="C_ARCHETYPE_ROOT">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.openehr.org/v1}C_COMPLEX_OBJECT">
 *       &lt;sequence>
 *         &lt;element name="archetype_id" type="{http://schemas.openehr.org/v1}ARCHETYPE_ID"/>
 *         &lt;element name="default_values" type="{http://schemas.openehr.org/v1}DEFAULT_VALUE" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="term_definitions" type="{http://schemas.openehr.org/v1}ARCHETYPE_TERM" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="term_bindings" type="{http://schemas.openehr.org/v1}TermBindingSet" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "C_ARCHETYPE_ROOT", propOrder = {
    "archetypeId",
    "defaultValues",
    "termDefinitions",
    "termBindings"
})
public class CARCHETYPEROOT
    extends CCOMPLEXOBJECT
{

    @XmlElement(name = "archetype_id", required = true)
    protected ARCHETYPEID archetypeId;
    @XmlElement(name = "default_values")
    protected List<DEFAULTVALUE> defaultValues;
    @XmlElement(name = "term_definitions")
    protected List<ARCHETYPETERM> termDefinitions;
    @XmlElement(name = "term_bindings")
    protected List<TermBindingSet> termBindings;

    /**
     * Gets the value of the archetypeId property.
     * 
     * @return
     *     possible object is
     *     {@link ARCHETYPEID }
     *     
     */
    public ARCHETYPEID getArchetypeId() {
        return archetypeId;
    }

    /**
     * Sets the value of the archetypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link ARCHETYPEID }
     *     
     */
    public void setArchetypeId(ARCHETYPEID value) {
        this.archetypeId = value;
    }

    /**
     * Gets the value of the defaultValues property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the defaultValues property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDefaultValues().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DEFAULTVALUE }
     * 
     * 
     */
    public List<DEFAULTVALUE> getDefaultValues() {
        if (defaultValues == null) {
            defaultValues = new ArrayList<DEFAULTVALUE>();
        }
        return this.defaultValues;
    }

    /**
     * Gets the value of the termDefinitions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the termDefinitions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTermDefinitions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ARCHETYPETERM }
     * 
     * 
     */
    public List<ARCHETYPETERM> getTermDefinitions() {
        if (termDefinitions == null) {
            termDefinitions = new ArrayList<ARCHETYPETERM>();
        }
        return this.termDefinitions;
    }

    /**
     * Gets the value of the termBindings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the termBindings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTermBindings().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TermBindingSet }
     * 
     * 
     */
    public List<TermBindingSet> getTermBindings() {
        if (termBindings == null) {
            termBindings = new ArrayList<TermBindingSet>();
        }
        return this.termBindings;
    }

}
