//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.06 at 01:43:49 PM CEST 
//


package org.openehr.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for C_CODE_REFERENCE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="C_CODE_REFERENCE">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.openehr.org/v1}C_CODE_PHRASE">
 *       &lt;sequence>
 *         &lt;element name="referenceSetUri" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "C_CODE_REFERENCE", propOrder = {
    "referenceSetUri"
})
public class CCODEREFERENCE
    extends CCODEPHRASE
{

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String referenceSetUri;

    /**
     * Gets the value of the referenceSetUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceSetUri() {
        return referenceSetUri;
    }

    /**
     * Sets the value of the referenceSetUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceSetUri(String value) {
        this.referenceSetUri = value;
    }

}
