//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.06 at 01:43:49 PM CEST 
//


package org.openehr.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for C_DV_STATE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="C_DV_STATE">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.openehr.org/v1}C_DOMAIN_TYPE">
 *       &lt;sequence>
 *         &lt;element name="assumed_value" type="{http://schemas.openehr.org/v1}DV_STATE" minOccurs="0"/>
 *         &lt;element name="value" type="{http://schemas.openehr.org/v1}STATE_MACHINE"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "C_DV_STATE", propOrder = {
    "assumedValue",
    "value"
})
public class CDVSTATE
    extends CDOMAINTYPE
{

    @XmlElement(name = "assumed_value")
    protected DVSTATE assumedValue;
    @XmlElement(required = true)
    protected STATEMACHINE value;

    /**
     * Gets the value of the assumedValue property.
     * 
     * @return
     *     possible object is
     *     {@link DVSTATE }
     *     
     */
    public DVSTATE getAssumedValue() {
        return assumedValue;
    }

    /**
     * Sets the value of the assumedValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link DVSTATE }
     *     
     */
    public void setAssumedValue(DVSTATE value) {
        this.assumedValue = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link STATEMACHINE }
     *     
     */
    public STATEMACHINE getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link STATEMACHINE }
     *     
     */
    public void setValue(STATEMACHINE value) {
        this.value = value;
    }

}
