//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.06 at 01:43:49 PM CEST 
//


package org.openehr.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DEFAULT_DV_ORDINAL complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DEFAULT_DV_ORDINAL">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.openehr.org/v1}DEFAULT_VALUE">
 *       &lt;sequence>
 *         &lt;element name="value" type="{http://schemas.openehr.org/v1}DV_ORDINAL"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DEFAULT_DV_ORDINAL", propOrder = {
    "value"
})
public class DEFAULTDVORDINAL
    extends DEFAULTVALUE
{

    @XmlElement(required = true)
    protected DVORDINAL value;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link DVORDINAL }
     *     
     */
    public DVORDINAL getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link DVORDINAL }
     *     
     */
    public void setValue(DVORDINAL value) {
        this.value = value;
    }

}
