//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.06 at 01:43:49 PM CEST 
//


package org.openehr.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DV_TIME_SPECIFICATION complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DV_TIME_SPECIFICATION">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.openehr.org/v1}DATA_VALUE">
 *       &lt;sequence>
 *         &lt;element name="value" type="{http://schemas.openehr.org/v1}DV_PARSABLE"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DV_TIME_SPECIFICATION", propOrder = {
    "value"
})
@XmlSeeAlso({
    DVPERIODICTIMESPECIFICATION.class,
    DVGENERALTIMESPECIFICATION.class
})
public abstract class DVTIMESPECIFICATION
    extends DATAVALUE
{

    @XmlElement(required = true)
    protected DVPARSABLE value;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link DVPARSABLE }
     *     
     */
    public DVPARSABLE getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link DVPARSABLE }
     *     
     */
    public void setValue(DVPARSABLE value) {
        this.value = value;
    }

}
