//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.17 at 05:12:14 PM CEST 
//


package org.openehr.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FLAT_ARCHETYPE_ONTOLOGY complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FLAT_ARCHETYPE_ONTOLOGY">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.openehr.org/v1}ARCHETYPE_ONTOLOGY">
 *       &lt;attribute name="archetype_id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FLAT_ARCHETYPE_ONTOLOGY")
public class FLATARCHETYPEONTOLOGY
    extends ARCHETYPEONTOLOGY
{

    @XmlAttribute(name = "archetype_id", required = true)
    protected String archetypeId;

    /**
     * Gets the value of the archetypeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArchetypeId() {
        return archetypeId;
    }

    /**
     * Sets the value of the archetypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArchetypeId(String value) {
        this.archetypeId = value;
    }

}
