//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.17 at 05:12:14 PM CEST 
//


package org.openehr.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for T_ATTRIBUTE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T_ATTRIBUTE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rm_attribute_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="children" type="{http://schemas.openehr.org/v1}T_COMPLEX_OBJECT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="differential_path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_ATTRIBUTE", propOrder = {
    "rmAttributeName",
    "children",
    "differentialPath"
})
public class TATTRIBUTE {

    @XmlElement(name = "rm_attribute_name", required = true)
    protected String rmAttributeName;
    protected List<TCOMPLEXOBJECT> children;
    @XmlElement(name = "differential_path", required = true)
    protected String differentialPath;

    /**
     * Gets the value of the rmAttributeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRmAttributeName() {
        return rmAttributeName;
    }

    /**
     * Sets the value of the rmAttributeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRmAttributeName(String value) {
        this.rmAttributeName = value;
    }

    /**
     * Gets the value of the children property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the children property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChildren().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TCOMPLEXOBJECT }
     * 
     * 
     */
    public List<TCOMPLEXOBJECT> getChildren() {
        if (children == null) {
            children = new ArrayList<TCOMPLEXOBJECT>();
        }
        return this.children;
    }

    /**
     * Gets the value of the differentialPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDifferentialPath() {
        return differentialPath;
    }

    /**
     * Sets the value of the differentialPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDifferentialPath(String value) {
        this.differentialPath = value;
    }

}
